### ISSUE TITLE
AGILE 2020 workshops

### ISSUE THREAD

**Issue by nuest** [o2r-project/agile-2017#27]
## Proposals

The current suggestion is two have two workshops: one about the guidelines, and one more practical. Interested people can attend both, but they can choose better.

Contributions to the proposals are welcome:

- Workshop I: https://docs.google.com/document/d/1OiL9nZqi2vLzOUDRennrWet0IGYojzmnw8P9WXCHCj0/edit
- Workshop II: https://docs.google.com/document/d/1TZ0BAgeivMpQRlbndniPft-kVlSg762qyXWk_vewyOc/edit

#### Tasks - proposal

- [x] reach out to the organisers and ask if they prefer two proposals, or just one and they make clear in descriptions etc. that people can attend/register for only parts.
- [x] everybody checks the proposals
- [x] submit, see https://agile-online.org/conference-2020/call-for-workshops-2020
- [x] add proposal PDFs to website repo

#### Tasks - after acceptance

- [x] create workshop website
- [ ] build (extend) organising team
- [ ] material: I suggest to create one OSF project per workshop, as component of the [main project](https://osf.io/phmce/).
  - take a good look at https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1007433

**Comment by nuest** [comment]
Workshops are accepted!

**Comment by nuest** [comment]
https://twitter.com/nordholmen/status/1214208738149699585

**Comment by nuest** [comment]
https://o2r.info/reproducible-agile/2020/

![image](https://user-images.githubusercontent.com/1325054/71828462-ad62f400-30a2-11ea-8ebe-17679aae60a5.png)
